# Generated by Django 6.0.7 on 2026-09-19 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_topic_room_host_message_room_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='room',
            name='roommates',
            field=models.ManyToManyField(blank=True, related_name='roommates', to=settings.AUTH_USER_MODEL),
        ),
    ]
